[package]
name = "game-ingestor"
version = "0.1.0"

[dependencies]
chess = "3.2.0"
pgn-reader = "0.22.0"
radix_trie = "0.2.1"
rocksdb = "0.19.0"
shakmaty = "0.23.0"
sysinfo = "0.27.7"
zstd = "0.12.2"
